#!/usr/bin/env bash

set -e

HOMETIME="18:00:00"
HOURS="$1"
LASTPASS_NAME="ProductivityTools/id_rsa"
file_name=${LASTPASS_NAME//\//-}
PRIVATE_KEY="/tmp/$file_name"

main() {
  if ! ssh-add -l | grep -q $file_name; then
    trap delete_private_key_file EXIT
    prompt_to_logout
    ensure_logged_in
    save_private_key_to_file
    add_private_key
  else
    echo "Key already exists"
  fi
}

prompt_to_logout() {
  if lpass status; then
    set +e
    lpass logout
    set -e
  fi
}

ensure_logged_in() {
  if ! lpass status > /dev/null 2>&1; then
    echo "Please enter your LastPass username to login:"
    read -r username
    lpass login "$username"
  fi
}

save_private_key_to_file() {
  delete_private_key_file
  lpass show "$LASTPASS_NAME" --notes > "$PRIVATE_KEY"
  chmod 400 "$PRIVATE_KEY"
}

add_private_key() {
    if [ -z "$HOURS" ]
    then
      add_private_key_until_hometime
    else
      add_private_key_for_x_hours
    fi
}

add_private_key_until_hometime() {
  local now until seconds_remaining

  now="$(date +%s)"
  until="$( date -j -f "%T" $HOMETIME +%s 2> /dev/null || date -d $HOMETIME +%s )"
  seconds_remaining=$((until - now))

  if [[ "$seconds_remaining" -lt 1 ]]; then
    echo "$HOMETIME is history. Go home!"
    exit 1
  else
    echo "Adding $LASTPASS_NAME until $HOMETIME..."
    ssh-add -t "$seconds_remaining" "$PRIVATE_KEY"
  fi
}

add_private_key_for_x_hours() {
  echo "Adding $LASTPASS_NAME for $HOURS hours..."
  ssh-add -t "${HOURS}h" "$PRIVATE_KEY"
}

delete_private_key_file() {
  rm -f "$PRIVATE_KEY"
}

main
